version: "3"

services:
  url-shorten:
    image: shubham192001/infracloud-urlshortner
    build: 
      context: "."
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    volumes:
      - ./.env:/workspace/.env
    env_file:
      - ./.env
    depends_on:
      - db


  db:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
    restart: always
    volumes:
      - redis-storage:/var/lib/redis

volumes:
  redis-storage:


    
