version: "3"

services:
  url-shorten:
    image: shubham192001/infracloud-urlshortner:0.6
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    depends_on:
      - db


  db:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
    restart: always
    volumes:
      - redis-storage:/var/lib/redis

volumes:
  redis-storage:


    
